services:
  postgres:
    image: postgres:16-alpine
    container_name: ensenia-postgres
    environment:
      POSTGRES_DB: ensenia
      POSTGRES_USER: ensenia
      POSTGRES_PASSWORD: hackathon
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ensenia"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
